Spectrum graph implem
monochromator/application pull request #1
Opened 2020-12-12 19:47 UTC by Tomansion

2020-12-12 19:48 UTC, Tomansion commented
![image](https://user-images.githubusercontent.com/59999324/101993469-5787ca80-3cbb-11eb-85ac-fef6a6726127.png)

2020-12-13 15:13 UTC, Thurstag requested changes

2020-12-13 15:13 UTC, Thurstag commented on ui/src/assets/lang/spectrum.json
> +            "yAxis_title": "Intensitée",
Intensité

2020-12-13 15:13 UTC, Thurstag commented on ui/src/assets/lang/spectrum.json
> +            "filter_btn_raw": "Données brut",
Données brutes

2020-12-13 15:13 UTC, Thurstag commented on ui/src/components/visu/Spectrum.vue
> +    // Todo : set the plotId to be randomly generated to avoid plot id concurency
Tu le fais dans cette PR ou dans une autre ?

2020-12-13 15:13 UTC, Thurstag commented on ui/src/components/visu/Spectrum.vue
> +    const longMax = 780;
On peut aller plus loin que 780, il se passe quoi si je te donne un graphe entre 780 et 900nm ?

2020-12-13 15:13 UTC, Thurstag commented on ui/src/components/visu/Spectrum.vue
> +    console.log(this.$t("spectrum.colorscale_title"));
console.log à enlever (bizarre que le lint ne soit pas triggered)

2020-12-13 16:01 UTC, Tomansion commented on ui/src/components/visu/Spectrum.vue
> +    const longMax = 780;
![image](https://user-images.githubusercontent.com/59999324/102016935-db958d00-3d63-11eb-9c2e-d58a09293bc8.png)
![image](https://user-images.githubusercontent.com/59999324/102016976-2b745400-3d64-11eb-9b6e-df54914d23e7.png)

On peut dépasser, c'est juste une indication pour indiquer le moment ou je n'ai plus de couleurs à afficher
![image](https://user-images.githubusercontent.com/59999324/102017056-ccfba580-3d64-11eb-93ec-928c5de52f75.png)

2020-12-13 16:02 UTC, Tomansion commented on ui/src/components/visu/Spectrum.vue
> +    // Todo : set the plotId to be randomly generated to avoid plot id concurency
c'est fait

2020-12-13 16:06 UTC, Tomansion commented on ui/src/components/visu/Spectrum.vue
> +    // Todo : set the plotId to be randomly generated to avoid plot id concurency
J'ai pu afficher plusieurs spectres

2020-12-13 17:59 UTC, Thurstag commented on ui/src/components/visu/Spectrum.vue
> +    const longMax = 780;
Ok nickel

2020-12-13 18:02 UTC, Thurstag requested changes

2020-12-13 18:02 UTC, Thurstag commented on ui/src/components/visu/Spectrum.vue
> +  private id = Math.random()
pas très fiable cet id, utilises plutôt: https://www.npmjs.com/package/uuid

2020-12-14 09:57 UTC, merged